name: Deploy to production S3

on:
  push:
    branches:
      - main

jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace Open Store Templates URL
        run: |
          grep -rl --exclude="*.yml" 'yampi-templates-sandbox' . | xargs -r sed -i 's/yampi-templates-sandbox/yampi-templates-main/g'

      - name: Replace Open Store CDN URL
        run: |
          grep -rl --exclude="*.yml" 'codigo-aberto-sandbox-assets' . | xargs -r sed -i 's/codigo-aberto-sandbox-assets/openstore-production-assets/g'

      - name: Replace Rocket CDN URL
        run: |
          grep -rl --exclude="*.yml" 'images-dev.yampi' . | xargs -r sed -i 's/images-dev.yampi/images.yampi/g'

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto replace yampi-templates-sandbox with yampi-templates-main"
          git push

  deploy:
    needs: replace-text
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.AWS_BUCKET }}/yampi-templates-main --delete --exclude ".github/*" --exclude ".git/*"
