name: Create ZIP on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: zip -r code.zip .

      - name: Upload ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: code-zip
          path: code.zip